<?php
namespace mpcmf\modules\defaultModule\controllers;

use mpcmf\modules\moduleBase\controllers\controllerBase;
use mpcmf\system\pattern\singleton;

/**
 * Class hitController
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\controllers;
 * @date 2016-07-29 11:45:30
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class hitController
    extends controllerBase
{

    use singleton;
}