<?php
namespace mpcmf\modules\defaultModule\controllers;

use mpcmf\modules\moduleBase\controllers\controllerBase;
use mpcmf\system\pattern\singleton;

/**
 * Class settingsController
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\controllers;
 * @date 2016-08-01 12:56:50
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class settingsController
    extends controllerBase
{

    use singleton;
}