<?php
namespace mpcmf\modules\defaultModule\entities;

use mpcmf\modules\moduleBase\entities\entityBase;
use mpcmf\system\pattern\singleton;

/**
 * Class hit
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\entities
 * @date 2016-07-29 11:45:30
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class hit
    extends entityBase
{

    use singleton;
}