<?php
namespace mpcmf\modules\defaultModule\entities;

use mpcmf\modules\moduleBase\entities\entityBase;
use mpcmf\system\pattern\singleton;

/**
 * Class settings
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\entities
 * @date 2016-08-01 12:56:50
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class settings
    extends entityBase
{

    use singleton;
}