<?php
namespace mpcmf\modules\defaultModule\actions;

use mpcmf\modules\moduleBase\actions\actionsBase;
use mpcmf\system\pattern\singleton;

/**
 * Class hitActions
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\actions;
 * @date 2016-07-29 11:45:30
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class hitActions
    extends actionsBase
{

    use singleton;

    /**
     * Set options inside this method
     *
     * @return mixed
     */
    public function setOptions()
    {
        // TODO: Implement setOptions() method.
    }

    /**
     * Bind some custom actions
     *
     * @return mixed
     */
    public function bind()
    {
        // TODO: Implement bind() method.
    }
}