<?php
namespace mpcmf\modules\defaultModule\actions;

use mpcmf\modules\moduleBase\actions\action;
use mpcmf\modules\moduleBase\actions\actionsBase;
use mpcmf\system\acl\aclManager;
use mpcmf\system\pattern\singleton;

/**
 * Class shlinkActions
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\actions;
 * @date 2016-07-29 11:38:42
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class shlinkActions
    extends actionsBase
{

    use singleton;

    /**
     * Set options inside this method
     *
     * @return mixed
     */
    public function setOptions()
    {
        // TODO: Implement setOptions() method.
    }

    /**
     * Bind some custom actions
     *
     * @return mixed
     * @throws \mpcmf\modules\moduleBase\exceptions\actionException
     */
    public function bind()
    {
        $this->registerAction('/', new action([
                'name' => 'Home',
                'method' => '__home',
                'path' => '/',
                'http' => [
                    'GET',
                ],
                'required' => [

                ],
                'template' => 'shurl/home.tpl',
                'useBase' => true,
                'relative' => false,
                'type' => action::TYPE__DEFAULT,
                'acl' => [
                    aclManager::ACL__GROUP_GUEST
                ],
            ], $this));
        $this->registerAction('shorten', new action([
                'name' => 'Shorten',
                'method' => '__shorten',
                'path' => '/~create',
                'http' => [
                    'GET',
                ],
                'required' => [

                ],
                'template' => 'shurl/shorten.tpl',
                'useBase' => true,
                'relative' => false,
                'type' => action::TYPE__DEFAULT,
                'acl' => [
                    aclManager::ACL__GROUP_GUEST
                ],
            ], $this));
    }
}