<?php
/**
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\module\mapper\settingsMapper
 * @date 2016-08-01 12:56:50
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
\mpcmf\system\configuration\config::setConfig(__FILE__, [
    'storage' => [
        'configSection' => 'default',
        'db' => 'burls',
        'collection' => 'settings'
    ]
]);