<?php
/**
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\module\mapper\shlinkMapper
 * @date 2016-07-29 11:38:42
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
\mpcmf\system\configuration\config::setConfig(__FILE__, [
    'storage' => [
        'configSection' => 'default',
        'db' => 'burls',
        'collection' => 'url'
    ]
]);