<?php
namespace mpcmf\modules\defaultModule\mappers;

use mpcmf\modules\moduleBase\mappers\mapperBase;
use mpcmf\system\pattern\singleton;

/**
 * Class hitMapper
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\mappers
 * @date 2016-07-29 11:45:30
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class hitMapper
    extends mapperBase
{

    use singleton;

    const FIELD___ID = '_id';
    const FIELD__IP = 'ip';
    const FIELD__JS = 'js';
    const FIELD__OTHER = 'other';
    const FIELD__SHORT = 'short';
    const FIELD__TM = 'tm';
    const FIELD__UA = 'ua';

    public function getPublicName()
    {
        return 'Link hit';
    }

    /**
     * Entity map
     *
     * @return array[]
     */
    public function getMap()
    {
        return [
            self::FIELD___ID => [
                'getter' => 'getMongoId',
                'setter' => 'setMongoId',
                'role' => array (
                  'key' => true,
                  'generate-key' => true,
                ),
                'name' => 'Mongo ID',
                'description' => 'Mongo ID',
                'type' => 'string',
                'formType' => 'text',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => false,
                  'unique' => true,
                ),
            ],
            self::FIELD__IP => [
                'getter' => 'getIp',
                'setter' => 'setIp',
                'role' => array (
                  'searchable' => true,
                  'sortable' => true,
                ),
                'name' => 'Ip',
                'description' => 'Ip',
                'type' => 'string',
                'formType' => 'text',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => true,
                  'unique' => false,
                ),
            ],
            self::FIELD__JS => [
                'getter' => 'getJs',
                'setter' => 'setJs',
                'role' => array (
                ),
                'name' => 'Js',
                'description' => 'Js',
                'type' => 'boolean',
                'formType' => 'checkbox',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => false,
                  'unique' => false,
                ),
            ],
            self::FIELD__OTHER => [
                'getter' => 'getOther',
                'setter' => 'setOther',
                'role' => array (
                ),
                'name' => 'Other',
                'description' => 'Other',
                'type' => 'array',
                'formType' => 'json',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => false,
                  'unique' => false,
                ),
            ],
            self::FIELD__SHORT => [
                'getter' => 'getShort',
                'setter' => 'setShort',
                'role' => array (
                  'searchable' => true,
                ),
                'name' => 'Short',
                'description' => 'Short',
                'type' => 'string',
                'formType' => 'text',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => true,
                  'unique' => false,
                ),
            ],
            self::FIELD__TM => [
                'getter' => 'getTm',
                'setter' => 'setTm',
                'role' => array (
                  'sortable' => true,
                ),
                'name' => 'Tm',
                'description' => 'Tm',
                'type' => 'int',
                'formType' => 'datetimepicker',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => true,
                  'unique' => false,
                ),
            ],
            self::FIELD__UA => [
                'getter' => 'getUa',
                'setter' => 'setUa',
                'role' => array (
                  'searchable' => true,
                ),
                'name' => 'Ua',
                'description' => 'Ua',
                'type' => 'string',
                'formType' => 'text',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => true,
                  'unique' => false,
                ),
            ],
        ];
    }
}