<?php
namespace mpcmf\modules\defaultModule\mappers;

use mpcmf\modules\moduleBase\mappers\mapperBase;
use mpcmf\system\pattern\singleton;

/**
 * Class settingsMapper
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\mappers
 * @date 2016-08-01 12:56:50
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class settingsMapper
    extends mapperBase
{

    use singleton;

    const FIELD___ID = '_id';
    const FIELD__KEY = 'key';
    const FIELD__VALUE = 'value';

    public function getPublicName()
    {
        return 'SHURL Settings';
    }

    /**
     * Entity map
     *
     * @return array[]
     */
    public function getMap()
    {
        return [
            self::FIELD__KEY => [
                'getter' => 'getKey',
                'setter' => 'setKey',
                'role' => array (
                  'key' => true,
                  'title' => true,
                  'searchable' => true,
                ),
                'name' => 'Key',
                'description' => 'Key',
                'type' => 'string',
                'formType' => 'text',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => true,
                  'unique' => true,
                ),
            ],
            self::FIELD__VALUE => [
                'getter' => 'getValue',
                'setter' => 'setValue',
                'role' => array (
                ),
                'name' => 'Value',
                'description' => 'Value',
                'type' => 'mixed',
                'formType' => 'json',
                'validator' => array (
                ),
                'relations' => array (
                ),
                'options' => array (
                  'required' => false,
                  'unique' => false,
                ),
            ],
        ];
    }
}