<?php
namespace mpcmf\modules\defaultModule\mappers;

use mpcmf\modules\moduleBase\mappers\mapperBase;
use mpcmf\system\pattern\singleton;

/**
 * Class shlinkMapper
 *
 *
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\mappers
 * @date 2016-07-29 11:38:42
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 */
class shlinkMapper
    extends mapperBase
{

    use singleton;

    const FIELD___ID = '_id';
    const FIELD__C_IP = 'c_ip';
    const FIELD__C_JS = 'c_js';
    const FIELD__C_TM = 'c_tm';
    const FIELD__C_UA = 'c_ua';
    const FIELD__ID = 'id';
    const FIELD__LONG = 'long';
    const FIELD__OTHER = 'other';
    const FIELD__SHORT = 'short';

    public function getPublicName()
    {
        return 'Short link';
    }

    /**
     * Entity map
     *
     * @return array[]
     */
    public function getMap()
    {
        return [
            self::FIELD___ID => [
                'getter' => 'getMongoId',
                'setter' => 'setMongoId',
                'role' => [
                ],
                'name' => 'Mongo ID',
                'description' => 'Mongo ID',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
            self::FIELD__C_IP => [
                'getter' => 'getCIp',
                'setter' => 'setCIp',
                'role' => [
                    'searchable' => true,
                    'sortable' => true,
                ],
                'name' => 'C ip',
                'description' => 'C ip',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => true,
                    'unique' => false,
                ],
            ],
            self::FIELD__C_JS => [
                'getter' => 'getCJs',
                'setter' => 'setCJs',
                'role' => [
                ],
                'name' => 'C js',
                'description' => 'C js',
                'type' => 'boolean',
                'formType' => 'checkbox',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
            self::FIELD__C_TM => [
                'getter' => 'getCTm',
                'setter' => 'setCTm',
                'role' => [
                    'sortable' => true,
                ],
                'name' => 'C tm',
                'description' => 'C tm',
                'type' => 'int',
                'formType' => 'datetimepicker',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => true,
                    'unique' => false,
                ],
            ],
            self::FIELD__C_UA => [
                'getter' => 'getCUa',
                'setter' => 'setCUa',
                'role' => [
                    'searchable' => true,
                ],
                'name' => 'C ua',
                'description' => 'C ua',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => true,
                    'unique' => false,
                ],
            ],
            self::FIELD__ID => [
                'getter' => 'getId',
                'setter' => 'setId',
                'role' => [
                    'key' => true,
                    'generate-key' => true,
                ],
                'name' => 'Id',
                'description' => 'Id',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => false,
                    'unique' => true,
                ],
            ],
            self::FIELD__LONG => [
                'getter' => 'getLong',
                'setter' => 'setLong',
                'role' => [
                ],
                'name' => 'Long',
                'description' => 'Long',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => true,
                    'unique' => false,
                ],
            ],
            self::FIELD__OTHER => [
                'getter' => 'getOther',
                'setter' => 'setOther',
                'role' => [
                ],
                'name' => 'Other',
                'description' => 'Other',
                'type' => 'array',
                'formType' => 'json',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => false,
                    'unique' => false,
                ],
            ],
            self::FIELD__SHORT => [
                'getter' => 'getShort',
                'setter' => 'setShort',
                'role' => [
                ],
                'name' => 'Short',
                'description' => 'Short',
                'type' => 'string',
                'formType' => 'text',
                'validator' => [
                ],
                'relations' => [
                ],
                'options' => [
                    'required' => true,
                    'unique' => false,
                ],
            ],
        ];
    }
}