<?php
namespace mpcmf\modules\defaultModule\models;

use mpcmf\modules\moduleBase\models\modelBase;
use mpcmf\system\pattern\singleton;

/**
 * Class hitModel
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\models
 * @date 2016-07-29 11:45:30
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 *
 * @method string getMongoId() Mongo ID
 * @method $this setMongoId(string $value) Mongo ID
 * @method string getIp() Ip
 * @method $this setIp(string $value) Ip
 * @method boolean getJs() Js
 * @method $this setJs(boolean $value) Js
 * @method array getOther() Other
 * @method $this setOther(array $value) Other
 * @method string getShort() Short
 * @method $this setShort(string $value) Short
 * @method int getTm() Tm
 * @method $this setTm(int $value) Tm
 * @method string getUa() Ua
 * @method $this setUa(string $value) Ua
 */
class hitModel
    extends modelBase
{

    use singleton;
}