<?php
namespace mpcmf\modules\defaultModule\models;

use mpcmf\modules\moduleBase\models\modelBase;
use mpcmf\system\pattern\singleton;

/**
 * Class settingsModel
 *
 *
  * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\defaultModule\models
 * @date 2016-08-01 12:56:50
 *
 * @author Gregory Ostrovsky <greevex@gmail.com>
 *
 * @method string getMongoId() Mongo ID
 * @method $this setMongoId(string $value) Mongo ID
 * @method string getKey() Key
 * @method $this setKey(string $value) Key
 * @method array getValue() Value
 * @method $this setValue(array $value) Value
 */
class settingsModel
    extends modelBase
{

    use singleton;
}